name: faunadb_data
description: This is a simple library that gives you CRUD operations for FAUNA.
version: 0.0.6
homepage: https://github.com/THM068/faunadb_data

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  faunadb_http: ^0.13.2
  optional: ^6.1.0+1
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
